### ISSUE TITLE
Scanner doesn't run in Windows in JetBrains extension

### ISSUE THREAD

**Issue by ahtrotta** [applandinc/appmap-intellij-plugin#124] opened 2022-09-15 21:35 UTC
Tested with RubyMine on Windows with Rails sample app.

The scanner is present in the folder `C:\Users\ahtro\AppData\JetBrains\appland-plugin\scanner\` but findings are not generated. If I manually execute the scanner with `scan --all` then findings are generated.

**Comment by jansorg** [comment] 2022-09-16 17:45
Is this a duplicate of https://github.com/applandinc/appmap-js/issues/726?

**Comment by ahtrotta** [comment] 2022-09-16 17:46
Yeah, looks like it is. Sorry, I didn't see that when I made this.

**Comment by jansorg** [comment] 2022-09-16 19:16
Duplicate of https://github.com/applandinc/appmap-js/issues/726

**Closed by jansorg** 2022-09-16 19:16 UTC
Labels: bug, intellij-analysis
